services: 
  cps542hw3: 
    build: https://github.com/meyersa/cps542hw3.git
    container_name: cps542hw3
    restart: always
    volumes:
      - "./results:/results"
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    